apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: voting-deploy
  name: voting-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voting-mapping
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: voting-mapping
    spec:
      containers:
      - image: kodekloud/examplevotingapp_vote:v1
        name: voting-app
        ports:
        - containerPort: 80
        resources: {}
status: {}
