apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: voting-app-service
  name: voting-app-service
spec:
  ports:
  - name: 80-80
    nodePort: 30004
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: voting-mapping
  type: NodePort
status:
  loadBalancer: {}
