apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: postgres-deploy
  name: postgres-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: postgres-deploy
    spec:
      containers:
      - image: postgres
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
status: {}
