apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: result-app-service
  name: result-app-service
spec:
  ports:
  - name: 80-80
    nodePort: 30005
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: result-app-service
  type: NodePort
status:
  loadBalancer: {}
